API_HOST_URL: 'http://localhost:8080' # mock server hostname in Android
ECOMMERCE_URL: 'http://localhost:8080' # mock server hostname in Android
ENVIRONMENT_DISPLAY_NAME: 'Localhost'
PLATFORM_NAME: 'Your platform name here'
PLATFORM_DESTINATION_NAME: 'example.com'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'
